create table if not exists public.site_settings (
  id bigint generated by default as identity primary key,
  company_name text default 'Andaman Trips',
  phone text,
  whatsapp text,
  email text,
  upi_id text,
  payee_name text,
  hero_title text,
  hero_subtitle text,
  hero_image text,
  updated_at timestamptz default now()
);

create table if not exists public.customers (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  phone text,
  email text,
  created_at timestamptz default now()
);

create table if not exists public.enquiries (
  id uuid primary key default gen_random_uuid(),
  customer_id uuid references public.customers(id),
  travel_date date,
  adults integer default 1,
  children integer default 0,
  destination text,
  package_name text,
  message text,
  status text default 'new',
  created_at timestamptz default now()
);

create table if not exists public.packages (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  duration text,
  price numeric default 0,
  image_url text,
  tag text,
  description text,
  active boolean default true,
  created_at timestamptz default now()
);

create table if not exists public.destinations (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  image_url text,
  description text,
  active boolean default true,
  created_at timestamptz default now()
);

create table if not exists public.hotels (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  location text,
  image_url text,
  description text,
  active boolean default true,
  created_at timestamptz default now()
);

create table if not exists public.activities (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  description text,
  price numeric default 0,
  image_url text,
  active boolean default true,
  created_at timestamptz default now()
);

create table if not exists public.quotations (
  id uuid primary key default gen_random_uuid(),
  customer_id uuid references public.customers(id),
  quotation_number text unique,
  total_amount numeric default 0,
  advance_amount numeric default 0,
  balance_amount numeric default 0,
  advance_mode text default 'fixed',
  status text default 'draft',
  notes text,
  created_at timestamptz default now()
);

create table if not exists public.bookings (
  id uuid primary key default gen_random_uuid(),
  customer_id uuid references public.customers(id),
  quotation_id uuid references public.quotations(id),
  booking_number text unique,
  status text default 'pending',
  created_at timestamptz default now()
);

create table if not exists public.payments (
  id uuid primary key default gen_random_uuid(),
  booking_id uuid references public.bookings(id),
  quotation_id uuid references public.quotations(id),
  amount numeric not null,
  status text default 'pending',
  screenshot_url text,
  verified_at timestamptz,
  created_at timestamptz default now()
);

create table if not exists public.reviews (
  id uuid primary key default gen_random_uuid(),
  customer_name text,
  rating integer default 5,
  review text,
  active boolean default true,
  created_at timestamptz default now()
);

create table if not exists public.email_templates (
  id uuid primary key default gen_random_uuid(),
  template_key text unique not null,
  subject text not null,
  html_body text not null,
  active boolean default true,
  updated_at timestamptz default now()
);

-- For the first setup, enable RLS and add policies deliberately after
-- the Supabase project is created. Do not expose the service-role key in Vite.
